import { Smooch_Sans } from 'next/font/google'
import './globals.css'

const ss = Smooch_Sans({ subsets: ['latin'], weight: ['800'] })

export const metadata = {
  title: 'Bassi tkm',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ss.className}>{children}</body>
    </html>
  )
}
